---
title: "z-test"
output: html_document
date: "2023-01-14"
---


Файл conversion.csv содержит данные для АВ-тестирования, проводимого с целью понять, приводит ли переход к новому типу меню к увеличению конверсии сайта.
Столбцы содержат значения 0 и 1, где 1 соответствует пользователю, который кликнул на меню и продолжил знакомство с сайтом, 0 – пользователю, который не стал продолжать знакомство с сайтом. Столбец OLD соответствует сайту со старым меню, а столбец NEW – сайту с новым меню.

1. Используя R, реализуйте статистический тест для сравнения двух долей, предполагая, что альтернативная гипотеза является правосторонней.

2. Сравните значения p-value, полученные в R и Python. Велика ли разница между ними? Влияет ли различие (если оно есть) на статистический вывод?

3. По результатам проверки гипотезы о равенстве долей, сделайте статистический и содержательный вывод.

```{r}

dat <- read.csv('6.7_conversion.csv')
ns1 <- sum(dat$OLD)
ns2 <- sum(dat$NEW)

n <- nrow(dat)

prop.test(c(ns1, ns2), c(n, n), alternative = 'less')

```
По итогу мы получили p-value очень близкое к нулю. Это означает, что со степенью значимости в 5% мы можем опровергнкть нулевую гипотезу о том, что конверсия сайта не изменилась, на текущих данных. 

Таким образом мы делаем вывод о том, что конверсия сайта увеличилась с переходом на новый тип меню
